import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'

import React from 'react'

const Cart: NextPage = () => {

  const router = useRouter()

  return (
    <div className="container bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2 className='my-5'>Pedidos</h2>
      <hr />

      <div className="row">
        {[
          { _id: '1', name: 'habibis'}
        ].map(item => (
          <div  key={item?._id} className='col-12'>
            <div className="card rounded-0 border-start-0 border-top-0 border-end-0" >
              <div className="card-body">

                <div className="d-flex flex-row align-items-center justify-content-between mb-3">
                  <h6 className="card-title mb-0">{item?.name}</h6>
                  <p className="card-text fw-semibold">R$ 24, 99</p>
                </div>

                <Link passHref shallow
                  href={{ pathname: router.pathname, query: { ...router.query, open: 'cart', storeName: 'habibs' } }}
                  as={`/cart/${'habibs'}`} 
                >
                  <a className="card-link text-decoration-none text-primary fw-semibold">Ver sacola</a>
                </Link>

                <Link passHref shallow href={`/product/${item._id}`} >
                  <a className="card-link text-decoration-none text-muted  fw-semibold">Remover</a>
                </Link>
              </div>
            </div>
          </div>
        ))}
      </div>

    </div>
  )
}

export default Cart
