import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'
import BagContext, { getId } from '../../contexts/bag'
import { MdRemove, MdAdd, MdStar, MdMoreHoriz } from 'react-icons/md'
import { IoMdEye } from 'react-icons/io'

import CloseButton from 'react-bootstrap/CloseButton';
import { Dropdown } from 'react-bootstrap' 
import { useRouter } from 'next/router'
import { Button } from 'react-bootstrap'

const Post: NextPage<any> = ({ vertical, component, className }) => {
  const router = useRouter()

  return (
    <div className={`card ${vertical ? 'border-desktop-only' : 'border-0 px-lg-3 pb-3'} px-0 ${className}`}>
      {!component && <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>}

        {/* <CloseButton className='position-absolute end-0 top-0 m-3 rounded-circle bg-white p-2' 
          onClick={() => router.back()}
        /> */}

        <div className={`row g-0 g-lg-5 my-0 mx-0 ${vertical ? '' : 'my-lg-4'}`}>

            <div className={`col-12 order-2 ${vertical ? '' : 'col-lg-6 order-lg-1 mt-lg-0'} px-0 mt-0`}>

              <div className="position-relative ">
                <div  className={`card-img-center ${vertical ? '' : 'rounded-desktop-only'} bg-secondary w-100 h-auto`} style={{ aspectRatio: "16/9" }} />
                  <Link passHref shallow
                    // href={router.query?.['productId'] ? router.pathname : `/?productId=${'abc1234'}`}
                    // as={router.query?.['productId'] ? router.pathname : `/product/${'abcd90'}`}
                    href={{ pathname: router.pathname, query: { ...router.query, productId: 'abcd90' } }}
                    as={`/product/${'abcd90'}`}
                  >
                    <a className="btn btn-transparent position-absolute top-50 start-50 translate-middle p-2 bg-white border border-light rounded-circle">
                      <span className="visually-hidden">New alerts</span>
                    </a>
                  </Link>
              </div>

            </div>
            
            <div className={`col-12 order-3 ${vertical ? '' : 'col-lg-6 order-lg-1 px-lg-3'} mt-0 px-0`}>
             <div className="card-body border-0">
                <p className="card-text">Favorited by <strong>ambaracadia</strong> and <strong>51</strong> others</p>
                <p className="card-text"><strong>Habibis</strong> esse hamburger com batatas são uma escolha ideal.</p>
              </div>
              <div className="card-footer border-0">
                <small className='opacity-50'>59 minutes ago</small>
              </div>
            </div>

            <div className={`col-12 order-1 ${vertical ? '' : 'col-lg-6 order-lg-1 mt-lg-3'} px-0 mt-0`}>

              <div className={`card-header rounded ${vertical ? '' : 'border-desktop-only'}`}>
                <div className="row">

                  <div className="col">
                    <div className="d-flex h-100 flex-row align-items-center">
                      <div  className="bg-secondary rounded-circle" style={{ height: 32, width: 32 }} />
                      <h6 className="card-title ms-2 mb-0">Card title</h6>
                    </div>
                  </div>

                  <div className="col">
                    <div className="d-flex h-100 flex-row align-items-center justify-content-end">
                      <button  className="btn btn-primary me-2">Favorite</button>
                      <Dropdown className='not-arrow'>
                        <Dropdown.Toggle 
                          as={Button}
                          variant="transparent" id="dropdown-basic" className='rounded-circle px-2'
                        >
                          <MdMoreHoriz size={24} />
                        </Dropdown.Toggle>

                        <Dropdown.Menu >
                          <Dropdown.Item className=' text-danger' href="#/action-3"><strong>Denunciar</strong></Dropdown.Item>
                          <Dropdown.Divider />
                          <Dropdown.Item className=' text-danger' href="#/action-2"><strong>Desfavoritar</strong></Dropdown.Item>
                          <Dropdown.Divider />
                          <Link passHref href={`/post/${'abc1234'}`}>
                            <Dropdown.Item>Ir para publicação</Dropdown.Item>
                          </Link>

                          <Dropdown.Divider />
                          <Dropdown.Item href="#/action-1">Copiar link</Dropdown.Item>
                        </Dropdown.Menu>
                      </Dropdown>
                    </div>
                  </div>

                </div>
              </div>

            </div>

        </div>

    </div>
  )
}

export default Post
