import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import Image from 'next/image'

import React from 'react'
import BagContext, { getId } from '../../contexts/bag'
import { MdRemove, MdAdd, MdStar, MdMoreHoriz, MdChevronLeft } from 'react-icons/md'
import { IoMdEye } from 'react-icons/io'

import CloseButton from 'react-bootstrap/CloseButton';
import { Dropdown, Carousel } from 'react-bootstrap' 
import { useRouter } from 'next/router'
import { Button } from 'react-bootstrap'
import { PresentationContext } from '../_app'


export const getServerSideProps: GetServerSideProps = async (context) => {
  
  return {
    props: { _id: 'server-side-id:'+context.query?.id }, // will be passed to the page component as props
  }
}

const Post: NextPage<any> = ({ _id, vertical, home, component, className }) => {
  const router = useRouter()

  const { setMemoryPosts } = React.useContext(PresentationContext)

  function handlePost () {
    setMemoryPosts(data)
  }


  const data = [
    { _id: 'io' }, 
    { _id: 'io2' }, 
    { _id: 'io3' }, 
    { _id: 'io4' }, 
    { _id: 'io5' },
    { _id: 'io6' },
    { _id: 'io7' },
    { _id: 'io8' },
  ].filter(item => item?._id !== (router.query?.postId || router.query?.id))

  return (
    <div className={`card ${vertical ? 'border-desktop-only' : 'border-0 px-lg-3'} px-0 ${className} ${component ? '' : 'bottom-tab-content-offset'}`}>
      {!component && <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>}

        <div className={`mobile-header-height d-inline d-lg-none ${(!component) ? '' : `${home ? 'd-none' : ''}` } sticky-top d-flex flex-row border-bottom align-item-center justify-content-between bg-light`} style={{ zIndex: 1 }}>
          <Button variant='transparent' className='' style={{ zIndex: 1 }}
            onClick={() => router.back()}
          >
            <MdChevronLeft size={32} />
          </Button>
          <div className="position-absolute d-flex align-items-center justify-content-center w-100 h-100 text-center">
            <h1 className='fs-5 mb-0'>Post</h1>
          </div>
        </div>

        <div className={`row g-0 g-lg-5 my-0 mx-0 ${vertical ? '' : 'mt-lg-4'}`}>

            <div className={`col-12 order-2 ${vertical ? '' : 'col-lg-6 order-lg-1 mt-lg-0'} px-0 mt-0`}>

              <div className={`position-relative overflow-hidden bg-secondary ${vertical ? '' : 'rounded-desktop-only py-lg-5'} `}>
                <div  className={`card-img-center bg-secondary w-100 h-auto`} style={{ aspectRatio: "16/9" }} >
                  <Image alt='post-img' src="/images/default-post.jpg" objectFit='cover' layout="fill" width={1080} height={566}  />
                </div>


                  <Link passHref shallow
                    // href={router.query?.['productId'] ? router.pathname : `/?productId=${'abc1234'}`}
                    // as={router.query?.['productId'] ? router.pathname : `/product/${'abcd90'}`}
                    href={{ pathname: router.pathname, query: { ...router.query, productId: 'abcd90' } }}
                    as={`/product/${'abcd90'}`}
                  >
                    <a className="btn btn-transparent position-absolute top-50 start-50 translate-middle p-2 bg-white border border-light rounded-circle">
                      <span className="visually-hidden">New alerts</span>
                    </a>
                  </Link>
              </div>

            </div>
            
            <div className={`col-12 order-3 ${vertical ? '' : 'col-lg-6 order-lg-2 px-lg-3'} mt-0 px-0`}>
            <div className="card-body border-0">
                <p className="card-text">Favorited by <strong>ambaracadia</strong> and <strong>51</strong> others</p>
                <p className="card-text"><strong>Habibis</strong> esse hamburger com batatas são uma escolha ideal.</p>
              </div>
              <div className="card-footer bg-transparent border-0">
                <small className='opacity-50'>59 minutes ago</small>
              </div>
            </div>

            <div className={`col-12 order-1 ${vertical ? '' : 'col-lg-12 order-lg-3 mt-lg-3'} px-0 mt-0`}>

              <div className={`card-header bg-transparent ${vertical ? '' : 'rounded-desktop-only border-desktop-only'}`}>
                <div className="row">

                  <div className="col">
                    <Link passHref shallow href={`/${'mateus'}`}>
                      <a className="d-flex h-100 flex-row align-items-center text-decoration-none">
                        <div  className="bg-secondary rounded-3 position-relative overflow-hidden" style={{ height: 42, width: 42 }} >
                          <Image alt='store-avatar-img' src="/images/default-store-avatar.webp" objectFit="cover" layout="fill" width={900} height={900} />
                        </div>
                        <h6 className="card-title text-dark ms-2 mb-0">Habibs - Mauá</h6>
                      </a>
                    </Link>
                  </div>

                  <div className="col">
                    <div className="d-flex h-100 flex-row align-items-center justify-content-end">
                      <Button variant="light" className="fw-semibold rounded-4 me-2 text-primary">
                        <small className="d-lg-none">Favorite</small>
                        <span className="d-none d-lg-block">Favorite</span>
                      </Button>
                      <Dropdown className='not-arrow'>
                        <Dropdown.Toggle 
                          as={Button}
                          variant="transparent" id="dropdown-basic" className='rounded-circle px-2'
                        >
                          <MdMoreHoriz size={24} />
                        </Dropdown.Toggle>

                        <Dropdown.Menu >
                          <Dropdown.Item className='text-danger fw-semibold' href="#/action-3">Denunciar</Dropdown.Item>
                          <Dropdown.Divider />
                          <Dropdown.Item className='text-danger fw-semibold' href="#/action-2">Desfavoritar</Dropdown.Item>
                          <Dropdown.Divider />
                          <Link passHref href={`/post/${'abc1234'}`}>
                            <Dropdown.Item>Ir para publicação</Dropdown.Item>
                          </Link>
                          <Dropdown.Divider />
                          <Dropdown.Item href="#/action-1">Copiar link</Dropdown.Item>
                        </Dropdown.Menu>
                      </Dropdown>
                    </div>
                  </div>

                </div>
              </div>

            </div>

        </div>


        <hr className={`${(!component) ? '' : `${home ? 'd-none' : 'd-lg-none'}` }`} />
        <p className={`ps-3 ${(!component) ? '' : `${home ? 'd-none' : 'd-lg-none'}` }`}>
          <span className='fw-bold text-muted'>Mais publicações de </span> 
          <Link passHref shallow href={`/${'mateus'}`}><a className='text-dark text-decoration-none'>{'mateus'}</a></Link>
        </p>
        <div className={`row gy-4 gx-0 gx-lg-4 gy-lg-4 mb-4 ${(!component) ? '' : `${home ? 'd-none' : 'd-lg-none'}` }`}>
          {data?.map(memoryPost => (
            <Link key={memoryPost?._id} passHref shallow scroll
              href={{ pathname: router.pathname, query: { ...router.query, postId: memoryPost?._id } }}
              as={`/post/${memoryPost?._id}`}
            >
              <a className='col-12 col-md-6 col-lg-4 text-decoration-none hover-bump' onClick={handlePost} >
                <div className='d-flex align-items-center justify-content-center bg-secondary rounded-desktop-only w-100 h-auto position-relative overflow-hidden' style={{ aspectRatio: "16/9" }}>
                  {/* <p className='text-white'>{memoryPost?._id}</p> */}
                  <Image alt='post-img' src="/images/default-post.jpg" objectFit='cover' layout="fill" width={1080} height={566}  />
                </div>
              </a>
            </Link>
          ))}
        </div>

    </div>
  )
}


export default Post

