import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

import React from 'react'
import BagContext, { getId } from '../../contexts/bag'
import { MdRemove, MdAdd, MdStar, MdChevronLeft } from 'react-icons/md'
import { IoMdEye } from 'react-icons/io'

import CloseButton from 'react-bootstrap/CloseButton';
import { useRouter } from 'next/router'
import { Button } from 'react-bootstrap'

const Product: NextPage<any> = ({ presentation }) => {
  const router = useRouter()
  
  const { bag, setBagItem, findBagItem } = React.useContext(BagContext)

  
  const item = {
    _id:'geneilson',
    name: 'item',
    price: 10,
    quantity: 0
  }

  const [quantity, setQuantity] = React.useState(findBagItem(item)?.quantity || 1);

  function handleSubmit () {
    setBagItem(item, quantity)
    router.back()
  }
  

React.useEffect(() => {
  console.log({ bag });
  
}, [bag])  


  return (
    <div className="container-fluid bottom-tab-content-offset px-0 px-lg-3 mb-lg-4" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {presentation && <CloseButton className='position-absolute end-0 top-0 m-3 rounded-circle bg-white p-2' 
          onClick={() => router.back()} style={{ zIndex: 1 }}
        />}

        {!presentation && (
          <Button variant='light' className='position-absolute d-lg-none opacity-75 start-0 top-0 m-3 rounded-circle px-2 ' 
            onClick={() => router.back()} style={{ zIndex: 1 }}
          >
            <MdChevronLeft size={24} />
          </Button>
        )}

        <div className="row g-0 g-lg-5 my-0 mx-0 mb-lg-4 mt-lg-4">
            <div className="col-12 px-0 col-lg-6 mt-lg-0">
              <div className="bg-secondary rounded-desktop-only w-100 h-auto position-relative overflow-hidden" style={{ aspectRatio: "16/9" }} >
                <Image alt='product-img' src="/images/default-product.webp" objectFit="cover" layout="fill" width={1080} height={720} />
              </div>
            </div>
            <div className="col-12 col-lg-6 mt-3 mt-lg-0 px-3">
              <h3 className="" >Hamburger</h3>
              <p>Pão Brioche, hamburguer artesanal de 140g, queijo prato, bacon crocante, molho barbecue , cebola roxa, alface e maionese hellmans .</p>
              <h6 className='text-success'>R$ 24,99</h6>
            </div>
        </div>

        <div className="row g-0">
          <div className="col-12 col-lg-6 px-3 px-lg-0 mt-3 mt-lg-0">

            <div className="py-2 border rounded px-3 py-1 h-100">
                <div className="d-flex flex-row align-items-center justify-content-between w-100">
                  <div className='d-flex align-items-center'>
                    <div className='rounded-3 bg-secondary position-relative overflow-hidden me-2' style={{ width: 42, height: 42 }} >
                      <Image alt='store-avatar-img' src="/images/default-store-avatar.webp" objectFit="cover" layout="fill" width={900} height={900} />
                    </div>
                    <h6 className='mb-0'>Habibis</h6>
                  </div>

                  <h6 className='mb-0 d-none d-lg-block'>30-40 min - <span className='text-success'>grátis</span></h6>

                  <div className='d-flex align-items-center text-warning'><MdStar size={24} /> <h6 className='mb-0'>4.5</h6></div>
                </div>
                <hr className='d-block d-lg-none' />
                <div className="d-flex flex-row align-items-center justify-content-between w-100 d-block d-lg-none">
                  <h6 className='mb-0'>30-40 min - <span className='text-success'>grátis</span></h6>
                </div>
            </div>

          </div>
          <div className="col-12 py-0 col-lg-6 product-bar-position-adapter bg-white bg-lg-transparent">
            <hr className='d-block d-lg-none my-0' />
            <div className="row py-1 g-2 g-lg-3 align-self-center align-items-center justify-content-between justify-content-lg-end h-100 px-3 px-lg-0">

              <div className="col-5 col-md-6 col-lg-5 h-100">


                  <div className="d-flex flex-row align-items-center justify-content-between border rounded px-3 py-1 h-100">

                    <Button disabled={!quantity} variant='transparent' className="p-1 px-2" onClick={() => setQuantity(quantity => quantity-1)}>
                      <MdRemove size={24} />
                    </Button>

                    <h6 className='p-1 px-2 mb-0 mx-1'>{quantity}</h6>

                    <Button variant='transparent' className="p-1 px-2" onClick={() => setQuantity(quantity => quantity+1)} >
                      <div className="d-flex align-items-center">
                        <MdAdd size={24} />
                      </div>
                    </Button>

                  </div>


              </div>

              <div className="col-7 col-md-6">
                <button onClick={() => handleSubmit()} className={`btn ${quantity ? 'btn-primary' : 'btn-danger'} py-3 px-3 h-100 w-100`}>
                  <div className="d-flex flex-row align-items-center px-1 justify-content-between">
                    <h6 className="mb-0">{quantity ? 'Adicionar' : 'Remover'}</h6>
                    <h6 className="mb-0">R$ 24,99</h6>
                  </div>
                </button> 
              </div>

            </div>
            {/* <hr className='d-block d-lg-none my-0 border-primary' /> */}
          </div>
        </div>
    </div>
  )
}

export default Product
