import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'
import BagContext, { getId } from '../../contexts/bag'
import { MdRemove, MdAdd, MdStar } from 'react-icons/md'
import { IoMdEye } from 'react-icons/io'

import CloseButton from 'react-bootstrap/CloseButton';
import { useRouter } from 'next/router'

const Product: NextPage = () => {

  const { bag, setBagItem, findBagItem } = React.useContext(BagContext)

  const item = {
    _id:'geneilson',
    name: 'item',
    price: 10,
    quantity: 0
  }

React.useEffect(() => {
  console.log({ bag });
  
}, [bag])  

const router = useRouter()

  return (
    <div className="container px-0 px-lg-3">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <CloseButton className='position-absolute end-0 rounded-circle bg-white p-2' 
          onClick={() => router.back()}
        />

        <div className="row g-0 g-lg-3 my-0 mx-0 mb-lg-4 mt-lg-4">
            <div className="col-12 px-0 col-lg-6 px-lg-3">
              <div className="bg-dark rounded w-100" style={{ height: 573/2 }} />
            </div>
            <div className="col-12 col-lg-6 mt-3 mt-lg-0">
              <h3 className="px-3 px-lg-0 " >Hamburger</h3>
            </div>
        </div>

        <div className="row g-0 g-lg-3">
          <div className="col-12 col-lg-6">

            <div className="d-flex flex-row align-items-center justify-content-between border rounded px-3 py-1 h-100">
                <div className='d-flex align-items-center'>
                  <div className='rounded-circle bg-dark me-2' style={{ width: 32, height: 32 }} /> 
                  <h6 className='mb-0'>Habibis</h6>
                </div>

                <h6 className='mb-0 d-none d-lg-block'>30-40 min - <span className='text-success'>grátis</span></h6>

                <div className='d-flex align-items-center text-warning'><MdStar size={24} /> <h6 className='mb-0'>4.5</h6></div>
            </div>

          </div>
          <div className="col-12 col-lg-6 product-bar-position-adapter">
            <div className="row g-0 g-lg-3 align-items-center justify-content-between justify-content-lg-end h-100">

              <div className="col-5 h-100">
                <div className="d-flex flex-row align-items-center justify-content-between border rounded px-3 py-1 h-100">

                  {
                    !!findBagItem(item) &&
                    <button className="btn btn-transparent p-1 px-2" onClick={() => setBagItem(item, (findBagItem(item)?.quantity||0)-1)}>
                      <MdRemove size={24} />
                    </button>
                  }
                  {
                    !!findBagItem(item) && 
                    <h6 className='p-1 px-2 mb-0 mx-1'>{findBagItem(item)?.quantity}</h6>
                  }

                  <button className="btn btn-transparent p-1 px-2" onClick={() => setBagItem(item, (findBagItem(item)?.quantity||0)+1)} >
                    <div className="d-flex align-items-center">
                      <MdAdd size={24} />
                      {!findBagItem(item) && 
                        <h6 className='mb-0 opacity-50 ms-2'>Quantidade</h6>
                      }
                    </div>
                  </button>

                  

                </div>
              </div>

              <div className="col-6">
                <button onClick={() => {}} className="btn btn-primary py-3 px-3 h-100 w-100">
                  <div className="d-flex flex-row align-items-center px-1 justify-content-between">
                    <h6 className="mb-0">Adicionar</h6>
                    <h6 className="mb-0">R$ 24,99</h6>
                  </div>
                </button> 
              </div>

            </div>

          </div>
        </div>
    </div>
  )
}

export default Product
