import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'

import React from 'react'
import { Button } from 'react-bootstrap'
import { MdChevronLeft } from 'react-icons/md'

const CheckoutStore: NextPage = () => {
  const router = useRouter()

  return (
    <div className="container bottom-tab-content-offset d-flex flex-column justify-content-between position-relative h-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}

export default CheckoutStore
