import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'

import React from 'react'
import { Button } from 'react-bootstrap'
import { MdChevronLeft } from 'react-icons/md'

const CartStore: NextPage = () => {
  const router = useRouter()

  return (
    <div className="container bottom-tab-content-offset d-flex flex-column justify-content-between position-relative h-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid">

        <div className="row my-5">
       
          <Button variant='link' className='w-auto text-decoration-none float-start text-primary fw-semibold' onClick={() => router.back()} >
            <MdChevronLeft /> Pedidos
          </Button>

          <div className="d-flex flex-row align-items-end justify-content-between">
            <h2 className='text-capitalize mb-0'>{router.query?.storeName}</h2>

            <Link passHref shallow href={`/${router.query?.storeName}`} >
              <a className="text-decoration-none text-primary fw-semibold">Ver Cardápio</a>
            </Link>
          </div>
        </div>

        <hr />

        <div className="row">
          {[
            { _id: '1', name: '1x Hamburger X'}
          ].map(item => (
            <div  key={item?._id} className='col-12'>
              <div className="card rounded-0 border-start-0 border-top-0 border-end-0" >
                <div className="card-body">

                  <div className="d-flex flex-row align-items-start justify-content-between mb-3">
                    <div>
                      <h6 className="card-title mb-0">{item?.name}</h6>
                      <p className="mb-0">1x Pão Brioche</p>
                    </div>
                    <p className="card-text fw-semibold">R$ 24, 99</p>
                  </div>

                  <Link passHref shallow href={`/product/${item._id}`} >
                    <a className="card-link text-decoration-none text-primary fw-semibold">Ver Item</a>
                  </Link>

                  <Link passHref shallow href={`/product/${item._id}`} >
                    <a className="card-link text-decoration-none text-muted  fw-semibold">Remover</a>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="row">
          <div className='col-12'>
            <div className="card rounded-0 border-0" >
              <div className="card-body">

                <div className="d-flex flex-row align-items-start justify-content-between">
                  <div className='text-start'>
                    <p className="mb-0 text-muted">Subtotal</p>
                    <p className="mb-0 text-muted">Taxa de entrega</p>
                  </div>
                  <div className='text-end'>
                    <p className="mb-0 text-success">R$ 24,99</p>
                    <p className="mb-0 text-success">Grátis</p>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
        
      </div>


      <div className="row m-0 sticky-bottom w-100" style={{ zIndex: 1 }}>
        <div className='col-12'>
          <div className="card rounded-0 border-0 mb-3" >
            <div className="card-body">

              <div className="d-flex flex-row align-items-start justify-content-between">
                  <p className="mb-0 text-muted">Total</p>
                  <p className="mb-0 text-success">R$ 499,00</p>
              </div>

            </div>
            <Link passHref shallow href={`/cart/${router.query?.storeName}/checkout`} >
              <Button as="a" variant='primary' className='py-lg-2' >Forma de pagamento</Button>
            </Link>
          </div>
        </div>
      </div>

    </div>
  )
}

export default CartStore
