import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'
import { useRouter } from 'next/router'
import { Dropdown, Button } from 'react-bootstrap'
import { MdFilter, MdFilterList, MdMoreHoriz } from 'react-icons/md'

import SearchInput from '../../components/SearchInput'
import { useDebounce, useDebounceState } from '../../hooks/useDebounce';

const Search: NextPage = () => {
  const router = useRouter()
  
  const [search, setSearch] = React.useState<string>((router.query?.search as string) || '')
  const debounce = useDebounce(search, 1000)

  return (
    <div className="container bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchInput className='d-lg-none mt-3' value={search} onChangeText={setSearch}
        handleSubmit={() => router.push(`/search/${search}`, undefined, { shallow: true })}
        history={['oi', 'hamburger']}
        debounce={debounce}
        suggestions={['hamburger', 'habibgs']}
      />

      <hr className='d-lg-none' />

      <h2 className="my-3 my-lg-5" >Buscar por: <span className='text-primary'>{router.query?.search}</span></h2>

      <button type="button" className="btn btn-outline-secondary border-2 rounded-pill mt-4 mt-lg-0">
        Filtrar<span className="ms-1"><MdFilterList /></span>
      </button>

      <div className='row g-1 g-md-3 mt-4'>
        {[
          { _id: '1' },
          { _id: '2' },
          { _id: '3' },
          { _id: '4' },
          { _id: '5' },
          { _id: '6' },
        ].map((item, key) => (
          <Link key={item._id}  passHref shallow 
            href={{ pathname: router.pathname, query: { ...router.query, productId: item?._id } }}
            as={`/product/${item?._id}`}
          >
            <a className='col-12 col-md-6 col-lg-4 text-decoration-none hover-bump'>
              <div className="card mb-3 overflow-hiden text-dark">
                <div className="row g-0">
                  <div className="col-7 col-md-6">
                    <div className="card-body">
                      <h6 className="card-title">Hamburger</h6>
                      <p className="card-text text-muted text-ellipsis-2">Pão Brioche, hamburguer artesanal de 140g, queijo prato, bacon crocante, molho barbecue , cebola roxa, alface e maionese hellmans .</p>
                      <p className="card-text"><strong className="text-success">R$ 22,99</strong></p>
                    </div>
                  </div>
                  <div className="col-5 col-md-6">
                    <div className='d-flex align-items-center justify-content-center bg-secondary rounded-end w-100 h-100 overflow-hidden position-relative' style={{ aspectRatio: "16/16" }}>
                      <Image alt='product-img' src="/images/default-product.webp" objectFit="cover" layout="fill" width={1080} height={720} />
                      {/* <p className='text-white' style={{ zIndex: 1 }}>{item?._id}</p> */}
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </Link>
        ))}
      </div>

      <div className="row">
        <Button variant="link" onClick={() => {}} className="text-decoration-none fw-semibold">Ver mais</Button>
      </div>

    </div>
  )
}

export default Search
