import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'
import { useRouter } from 'next/router'

import SearchInput from '../../components/SearchInput'
import { useDebounce, useDebounceState } from '../../hooks/useDebounce';

const SearchEmpty: NextPage = () => {
  const router = useRouter()
  
  const [search, setSearch] = React.useState<string>((router.query?.search as string) || '')
  const debounce = useDebounce(search, 1000)

  return (
    <div className="container bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchInput className='d-lg-none mt-3' value={search} onChangeText={setSearch}
        handleSubmit={() => router.push(`/search/${search}`, undefined, { shallow: true })}
        history={['oi', 'hamburger']}
        debounce={debounce}
        suggestions={['hamburger', 'habibgs']}
      />

      <hr className='d-lg-none' />

      <h2 className="mb-5 my-lg-5" >Categorias</h2>

      <div className="row g-1 g-md-3">
        {[
          { _id: '1', name: 'Bebidas' },
          { _id: '2', name: 'Pizzas' },
          { _id: '3', name: 'Hamburgers' },
          { _id: '4', name: 'Refrigerantes' },
        ]?.map((item, key) => (
          <Link key={key}  passHref shallow 
            href={`/search/${item?.name}`}
          >
            <a className='col-6 col-md-6 col-lg-4 text-decoration-none' onClick={() => {}} >
              {/* <div className='d-flex bg-secondary rounded-desktop-only w-100 h-auto position-relative overflow-hidden' style={{ aspectRatio: "16/9" }}>
                <div className="d-flex flex-fill p-2 p-md-3 p-lg-4 position-relative" style={{ zIndex: 1 }}>
                  <div className="h-100" />
                  <h5 className='text-white'>{item?.name}</h5>
                </div>
              </div> */}

              <div className="card border text-bg-dark rounded-desktop-only w-100 h-auto position-relative overflow-hidden" style={{ aspectRatio: "16/9" }}>
                <Image className="opacity-50" alt='category-img' src="/images/default-category.webp" objectFit="cover" layout="fill" width={331} height={143} />
                <div className="card-img-overlay">
                  <h5 className="card-title">{item?.name}</h5>
                  {/* <p className="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> */}
                  {/* <p className="card-text">Last updated 3 mins ago</p> */}
                </div>
              </div>

            </a>
          </Link>
        ))}
      </div>
    </div>
  )
}

export default SearchEmpty
