import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'
import { useRouter } from 'next/router'

const SearchEmpty: NextPage = () => {

  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h4 className="text-center my-5" >Search Empty</h4>

    </div>
  )
}

export default SearchEmpty
