import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'
import BagContext, { getId } from '../../contexts/bag'
import { MdRemove, MdAdd, MdStar, MdMoreHoriz } from 'react-icons/md'
import { IoMdEye } from 'react-icons/io'

import CloseButton from 'react-bootstrap/CloseButton';
import { Dropdown } from 'react-bootstrap' 
import { useRouter } from 'next/router'
import { Button } from 'react-bootstrap'
import { PresentationContext } from '../_app'

const Store: NextPage<any> = ({ vertical, component, className }) => {
  const router = useRouter()

  const { setMemoryPosts } = React.useContext(PresentationContext)

  const data = [
    { _id: '1' },
    { _id: '2' },
    { _id: '3' },
    { _id: '4' },
    { _id: '5' },
    { _id: '6' },
  ];

  return (
    <div className={`card ${vertical ? 'border-desktop-only' : 'border-0 px-lg-3 pb-3'} px-0 ${className}`}>
      {!component && <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>}

        <div className="row">
          {data?.map((item, key) => (
            <Link key={key}  passHref shallow 
              href={{ pathname: router.pathname, query: { ...router.query, postId: item?._id } }}
              as={`/${'mateus'}/post/${item?._id}`}
            >
              <a className='col-3' onClick={() => setMemoryPosts(data)} >
                <div className='bg-dark w-100 h-auto' style={{ aspectRatio: "16/9" }}>
                  <p className='text-white'>{item?._id}</p>
                </div>
              </a>
            </Link>
          ))}
        </div>

    </div>
  )
}

export default Store
