import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

import React from 'react'
import BagContext, { getId } from '../../contexts/bag'
import { MdRemove, MdAdd, MdStar, MdMoreHoriz, MdLocalOffer, MdChevronLeft } from 'react-icons/md'
import { IoMdEye } from 'react-icons/io'

import CloseButton from 'react-bootstrap/CloseButton';
import { Dropdown } from 'react-bootstrap' 
import { useRouter } from 'next/router'
import { Button, Tabs, Tab } from 'react-bootstrap'
import { PresentationContext } from '../_app'

import Scrollspy from 'react-scrollspy'

const Store: NextPage<any> = ({ vertical, component, className }) => {
  const router = useRouter()

  const { setMemoryPosts } = React.useContext(PresentationContext)

  const data = [
    { _id: '1' },
    { _id: '2' },
    { _id: '3' },
    { _id: '4' },
    { _id: '5' },
    { _id: '6' },
  ];

  const menuData = [
    { 
      _id: 'gene1',
      title: 'hamburgers', 
      items: [
        { _id: '1' },
        { _id: '2' },
        { _id: '3' },
        { _id: '4' },
        { _id: '5' },
        { _id: '6' },
      ] 
    },
    { 
      _id: 'gene2',
      title: 'pizzas', 
      items: [
        { _id: '1' },
        { _id: '2' },
        { _id: '3' },
        { _id: '4' },
        { _id: '5' },
        { _id: '6' },
      ] 
    },
  ];

  const [id, setId] = React.useState<string>('')

  return (
    <div className='container bottom-tab-content-offset'>
      {!component && <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>}

      <div className={`mobile-header-height d-inline d-lg-none sticky-top d-flex flex-row border-bottom align-item-center justify-content-between bg-light`} style={{ zIndex: 1 }} >
          <Button variant='transparent' className='' style={{ zIndex: 1 }}
            onClick={() => router.back()}
          >
            <MdChevronLeft size={32} />
          </Button>
          <div className="position-absolute d-flex align-items-center justify-content-center w-100 h-100 text-center">
            <h1 className='fs-5 mb-0'>Store</h1>
          </div>
      </div>

        <div className="d-flex flex-row mt-4 mt-lg-5 mb-3">
          <div>
            <div className="bg-secondary rounded-4 position-relative overflow-hidden" style={{ height: 82, width: 82 }} >
              <Image alt='store-avatar-img' src="/images/default-store-avatar.webp" objectFit="cover" layout="fill" width={900} height={900} />
            </div>
          </div>

          <div className="row ms-0 ms-md-2 ms-lg-4">
            <div className="col-12 col-md-8">
              <div className='d-flex flex-column w-100' >
                <div className="d-flex flex-row align-items-center mb-1">
                  <h3 className="card-title m-0">Habibis</h3>
                  <h6 className='text-warning ms-2 m-0 d-none d-lg-inline'><span className='align-text-top'><MdStar/></span> 4.5</h6>
                </div>

                <small className='mb-0 mb-lg-3 text-ellipsis-2'>Pão Brioche, hamburguer artesanal de 140g, queijo prato, bacon crocante, molho barbecue , cebola roxa, alface e maionese hellmans .</small>
                
              </div>
            </div>

            <div className="col-12 col-md-4">
              <small className='w-100 text-start text-lg-end float-end'><span className='text-primary fw-semibold'>Ver mais</span> - pedido minimo de R$ 20,00</small>
              {/* <Button variant='primary' className='float-start float-lg-end'>Favorite</Button> */}
            </div>

          </div>

        </div>

        <div className="row g-0 mb-3">
          <div className="col-12">
            <div className="border-mobile-only py-2 px-3 rounded">
              <small>
                <span className='text-primary fw-semibold'><span className='align-text-bottom'><MdLocalOffer /></span> Entrega grátis </span> a partir de <span className='fw-semibold'>R$ 55,00</span><span className='fw-semibold d-none d-lg-inline'> - 30-40 min - <span className='text-success fw-semibold'>grátis</span></span>
              </small>
              <hr className='d-lg-none my-2' />
              <small className='d-inline d-lg-none'>
                <span className='fw-semibold'>R$ 55,00 - 30-40 min - </span><span className='text-success fw-semibold'>grátis</span>
              </small>
              <h6 className='text-warning fw-semibold float-end ms-2 m-0 d-inline d-lg-none'><span className='align-text-top'><MdStar/></span> 4.5</h6>
            </div>
          </div>
        </div>

        <div className="row">

          <Tabs id="uncontrolled-tab-example"
            defaultActiveKey="menu"
            className="mb-3" 
            style={{ zIndex: 1 }}
          >
            <Tab eventKey="menu" title="Cardápio">
              <Scrollspy items={menuData.map(item => item.title)} className="navbar sticky-top header-offset-top bg-white border-bottom px-3 pb-0 mb-3"
                currentClassName='text-success'  
                scrolledPastClassName='text-success'
                onUpdate={(e: { id: string }) => e?.id && setId(e?.id)}
                offset={56} style={{ zIndex: 1 }}
              >
                <ul className="nav" >
                  {menuData.map(item => (
                    <li key={item.title} className={`nav-item ${id === item.title ? 'border-bottom border-2 border-primary' : ''}`}>
                      <Link passHref shallow replace href={`#${item.title}`} as={{ href: `/${router.query?.store}`, hash: `#${item.title}` }}>
                        <a className={`nav-link fs-6 fw-semibold ${id === item.title ? 'active' : 'text-dark'}`} >
                          {item.title}
                        </a>
                      </Link>
                    </li>
                  ))}
                </ul>
              </Scrollspy >
              {menuData.map((section, key) => (
                <div key={section?._id} className="row g-1 g-md-3">
                  <div className="col-12 py-3">
                    <h4 className='anchor text-muted' id={section.title} >{section.title}</h4>
                  </div>
                  <div className="col-12">
                    <div className="row g-1 g-md-3">
                      {section.items.map((item, key) => (
                        <Link key={key}  passHref shallow 
                          href={{ pathname: router.pathname, query: { ...router.query, productId: item?._id } }}
                          as={`/product/${item?._id}`}
                          >
                          <a key={key} className='col-12 col-md-6 col-lg-4 text-decoration-none'
                            onClick={async (e) => {
                              e.preventDefault()
                              setId(section.title)
                              await router.replace(`/${router.query?.store}`, `/${router.query?.store}`, { shallow: true, scroll: false })
                              await router.push({ pathname: router.pathname, query: { ...router.query, productId: item?._id } }, `/product/${item?._id}`, { shallow: true, scroll: false })
                            }}
                          >
                            <div className="card mb-3 overflow-hiden text-dark">
                              <div className="row g-0">
                                <div className="col-7 col-md-6">
                                  <div className="card-body">
                                    <h6 className="card-title">Hamburger</h6>
                                    <p className="card-text text-muted text-ellipsis-2">Pão Brioche, hamburguer artesanal de 140g, queijo prato, bacon crocante, molho barbecue , cebola roxa, alface e maionese hellmans .</p>
                                    <p className="card-text"><strong className="text-success">R$ 22,99</strong></p>
                                  </div>
                                </div>
                                <div className="col-5 col-md-6">
                                  <div className='d-flex align-items-center justify-content-center bg-secondary rounded-end w-100 h-100 position-relative overflow-hidden' style={{ aspectRatio: "16/16" }}>
                                    {/* <p className='text-white'>{item?._id}</p> */}
                                    <Image alt='product-img' src="/images/default-product.webp" objectFit="cover" layout="fill" width={1080} height={720} />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </a>
                        </Link>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </Tab>
            <Tab eventKey="posts" title="Postagens">
                <div className="row g-1 g-md-3">
                  {data?.map((item, key) => (
                    <Link key={key}  passHref shallow 
                      href={{ pathname: router.pathname, query: { ...router.query, postId: item?._id } }}
                      as={`/post/${item?._id}`}
                    >
                      <a className='col-6 col-md-4 col-lg-3 text-decoration-none' onClick={() => setMemoryPosts(data)} >
                        <div className='d-flex align-items-center justify-content-center bg-secondary rounded-desktop-only w-100 h-auto position-relative overflow-hidden' style={{ aspectRatio: "16/9" }}>
                          {/* <p className='text-white'>{item?._id}</p> */}
                          <Image alt='post-img' src="/images/default-post.jpg" objectFit='cover' layout="fill" width={1080} height={566}  />
                        </div>
                      </a>
                    </Link>
                  ))}
                </div>
            </Tab>

          </Tabs>

        </div>


    </div>
  )
}

export default Store
