import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import { Button, Dropdown } from 'react-bootstrap'

import React from 'react'
import { MdChevronRight, MdFavoriteBorder, MdHelp, MdLogout, MdOutlineFavorite, MdOutlineHelpOutline, MdOutlineShoppingBag, MdSecurity } from 'react-icons/md'

const Account: NextPage = () => {

  return (
    <div className="container bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h4 className="text-center mt-4 mb-4 text-muted" >Olá Mateus</h4>

      <hr />

      <ol className="list-group list-group-flush">
        {[
          { Icon: MdFavoriteBorder, name: 'Favoritos' },
          { Icon: MdOutlineShoppingBag, name: 'Pedidos' },
          { Icon: MdSecurity, name: 'Segurança' },
          { Icon: MdOutlineHelpOutline, name: 'Ajuda' },
          { Icon: MdLogout, name: 'Sair' },
        ].map(({ Icon, name }, key) => (
          <li key={key} className="list-group-item p-0 border-0">
            <Link passHref shallow href={'#'}>
              <Dropdown.Item bsPrefix="none" as="a" className='btn btn-link d-flex my-1 justify-content-between align-items-center text-dark text-decoration-none px-3 py-3'>
                <Icon size={24} />
                <div className="ms-4 me-auto">
                  <div className="fw-semibold">{name}</div>
                  {/* Content for list item */}
                </div>
                {/* <span className="badge bg-primary rounded-pill">14</span> */}
                <span className='ms-4'><MdChevronRight /></span>
              </Dropdown.Item>
            </Link>
          </li>
        ))}
      </ol>

    </div>
  )
}

export default Account

