import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'

const Andress: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h4 className="text-center my-5" >Onde você quer receber seu pedido?</h4>

      <div className="text-center mb-5">
        <p>Já tem um endereço salvo?</p>
        <p>Entre na sua conta para selecionar seu endereço.</p>
      </div>

      <div className="d-flex justify-content-center mb-5">
        <Link href={'#'}>
          <a className='p-1 text-primary fw-semibold text-decoration-none'>Entrar ou cadastrar</a>
        </Link>
      </div>
    </div>
  )
}

export default Andress
