import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'

import { Button, CloseButton } from 'react-bootstrap'
import { MdChevronLeft, MdLocalActivity, MdMyLocation } from 'react-icons/md' 
import { useRouter } from 'next/router'
import SearchInput from '../components/SearchInput'
import { useDebounce } from '../hooks/useDebounce'

const Andress: NextPage<any> = ({ presentation }) => {
  const [search, setSearch] = React.useState<string>('')
  const debounce = useDebounce(search, 1000)

  const router = useRouter()

  return (
    <div className="container pt-4 bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!presentation && (
        <div className={`mobile-header-height sticky-top d-flex d-lg-none flex-row border-bottom align-item-center justify-content-between bg-light`} style={{ zIndex: 1 }}>
          
          <Button variant='transparent' className='d-inline d-lg-none' style={{ zIndex: 1 }}
            onClick={() => router.back()}
          >
            <MdChevronLeft size={32} />
          </Button>
          
          <div className="position-absolute d-flex align-items-center justify-content-center w-100 h-100 text-center">
            <h1 className='fs-5 mb-0'>Post</h1>
          </div>

        </div>
      )}
      
      {presentation && <CloseButton className='position-absolute end-0 top-0 m-3 rounded-circle bg-white p-2' 
        onClick={() => router.back()}
      />}

      <h4 className="text-center my-5" >Onde você quer receber seu pedido?</h4>

      <div className="row mt-4 mb-3 mx-5 px-5">
        <SearchInput className='m-0 p-0' 
          placeholder={'Buscar endereço e número'}
          value={search} onChangeText={setSearch}
          handleSubmit={() => router.push(`/search/${search}`, undefined, { shallow: true })}
          history={['oi', 'hamburger']}
          debounce={debounce}
          suggestions={['hamburger', 'habibgs']}
        />
      </div>

      <div className="row mt-3 mb-4 mx-5 px-5">
        <Button variant='outline-secondary text-start' className='' >
          <MdMyLocation size={24} />
          <span className='ms-2 align-text-top'>Usar minha localização</span>
        </Button>
      </div>

      <div className="text-center mb-5">
        <p>Já tem um endereço salvo?</p>
        <p>Entre na sua conta para selecionar seu endereço.</p>
      </div>

      <div className="d-flex justify-content-center mb-5">
        <Link href={'#'}>
          <a className='p-1 text-primary fw-semibold text-decoration-none'>Entrar ou cadastrar</a>
        </Link>
      </div>
    </div>
  )
}

export default Andress
