import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'

import { Button, CloseButton } from 'react-bootstrap'
import { MdChevronLeft } from 'react-icons/md' 
import { useRouter } from 'next/router'

const Andress: NextPage<any> = ({ presentation }) => {

  const router = useRouter()

  return (
    <div className="container pt-4 bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!presentation && (
        <div className={`mobile-header-height sticky-top d-flex d-lg-none flex-row border-bottom align-item-center justify-content-between bg-light`} style={{ zIndex: 1 }}>
          
          <Button variant='transparent' className='d-inline d-lg-none' style={{ zIndex: 1 }}
            onClick={() => router.back()}
          >
            <MdChevronLeft size={32} />
          </Button>
          
          <div className="position-absolute d-flex align-items-center justify-content-center w-100 h-100 text-center">
            <h1 className='fs-5 mb-0'>Post</h1>
          </div>

        </div>
      )}
      
      {presentation && <CloseButton className='position-absolute end-0 top-0 m-3 rounded-circle bg-white p-2' 
        onClick={() => router.back()}
      />}

      <h4 className="text-center my-5" >Onde você quer receber seu pedido?</h4>

      <div className="text-center mb-5">
        <p>Já tem um endereço salvo?</p>
        <p>Entre na sua conta para selecionar seu endereço.</p>
      </div>

      <div className="d-flex justify-content-center mb-5">
        <Link href={'#'}>
          <a className='p-1 text-primary fw-semibold text-decoration-none'>Entrar ou cadastrar</a>
        </Link>
      </div>
    </div>
  )
}

export default Andress
