import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HeaderDesktopOnly from '../components/HeaderDesktopOnly'
import styles from '../styles/Home.module.css'
import { MdMoreHoriz } from 'react-icons/md';

import { Offcanvas, CloseButton } from 'react-bootstrap';

import React from 'react'
import Post from '../components/Post'
import BagContext from '../contexts/bag'
import api from '../services/api'

const Home: NextPage = () => {

  const { bag, saveInBag, removeInBag, updateInBag } = React.useContext(BagContext)

  React.useEffect(() => {
    api.get('/fruit/all').then(response => {
      console.log({ response });
      
    })
  }, [])

  return (
    <div className="container g-0 g-md-3">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className="row p-0 m-0">

          <div className="col-12 col-lg-6 p-0 px-md-4 mx-md-2 mt-4">
            <Post />
            <Post />
            <Post />
            <Post />
          </div>

          <div className="col-lg-6">

          </div>

        </div>
    </div>
  )
}

export default Home
