import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import HeaderDesktopOnly from '../components/HeaderDesktopOnly'
import styles from '../styles/Home.module.css'
import { MdMoreHoriz, MdExpandMore, MdOutlineHome, MdFavoriteBorder, MdChevronRight } from 'react-icons/md';

import { Offcanvas, CloseButton, Navbar, Nav, Container, NavDropdown, Dropdown } from 'react-bootstrap';

import React from 'react'
import Post from './post/[id]'
import BagContext from '../contexts/bag'
import api from '../services/api'

import Link from 'next/link'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()

  React.useEffect(() => {
    api.get('/fruit/all').then(response => {
      console.log({ response });
      
    })
  }, [])

  return (
    <div className="container g-0 g-md-3 bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar style={{ zIndex: 1 }} sticky='top' bg='white' className='border-bottom d-lg-none align-items-center' expand="sm">
        <Container className='h-100 align-items-center justify-content-start position-relative'>

          <Link passHref href='/' replace >
            <Navbar.Brand className='me-0' onClick={() => {}} >
              insta-delivery
            </Navbar.Brand>
          </Link> 
          <NavDropdown className='not-arrow mx-2' title={<MdExpandMore className='opacity-75' size={16} />}  id="collasible-nav-dropdown">
              <ol className="list-group list-group-flush px-2">
                {[
                    { Icon: MdOutlineHome, name: 'Home', href: '/' },
                    { Icon: MdFavoriteBorder, name: 'Favoritos', href: '/?variant=favorites' },
                  ].map(({ Icon, name, href }, key) => (
                    <li key={key} className="list-group-item p-0">
                      <Link passHref shallow href={href}>
                        <Dropdown.Item bsPrefix="none" as="a" className='btn btn-link d-flex my-1 justify-content-between align-items-center text-dark text-decoration-none px-3 py-2'
                          onClick={() => {}}
                        >
                          <Icon size={20} />
                          <div className="ms-3 me-auto">
                            <div className="fw-semibold">{name}</div>
                            {/* Content for list item */}
                          </div>
                          {/* <span className="badge bg-primary rounded-pill">14</span> */}
                          <span className='ms-4'><MdChevronRight /></span>
                        </Dropdown.Item>
                      </Link>
                    </li>
                  ))}
              </ol>
            </NavDropdown>

            <Nav className="col-6 mt-1 ms-auto">

                <Link passHref shallow
                  href={{ pathname: router.pathname, query: { ...router.query, open: 'andress' } }}
                  as={`/andress`}
                  scroll={false}
                >
                  <Nav.Link className="position-relative pe-3"
                    disabled={router.pathname === '/andress'} 
                    active={router.pathname === '/andress'}
                    // onClick={props?.onOpenModal}
                  >
                    <span className='text-ellipsis-1'>Próximo de Jardim Maria Eneida Rua Antonia de oliveira, n53</span>
                    <span className="position-absolute top-50 end-0 translate-middle">
                      <MdExpandMore />
                    </span>
                  </Nav.Link>
                </Link>          
              
            </Nav>

        </Container>
      </Navbar>

        <div className="row p-0 m-0">

          <div className="col-12 col-lg-6 p-0 px-md-4 mx-md-2 mt-4">
           {[1,2,3,4,5].map((item, index) => 
            <Post key={index} home component vertical className="mb-3" />
           )}
          </div>

          <div className="col-lg-6">

          </div>

        </div>
    </div>
  )
}

export default Home
