import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import React from 'react'

import { Button, CloseButton } from 'react-bootstrap'
import { MdArrowBackIos, MdArrowBackIosNew, MdChevronLeft, MdLocalActivity, MdMyLocation } from 'react-icons/md' 
import { useRouter } from 'next/router'
import SearchInput from '../components/SearchInput'
import { useDebounce } from '../hooks/useDebounce'

const SignUp: NextPage<any> = ({ presentation }) => {

  const router = useRouter()

  return (
    <div className="container pt-4 bottom-tab-content-offset">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!presentation && (
        <Button variant='light' className='position-absolute d-lg-none start-0 top-0 m-3 rounded-circle px-2 border-2 text-dark border' 
          onClick={() => router.back()} style={{ zIndex: 1 }}
        >
          <MdArrowBackIosNew style={{ marginLeft: -2 }} size={24} />
        </Button>
      )}

      <div className="row align-items-center justify-content-center mt-0 mt-lg-3">

        <div className="col-11 col-md-7 col-lg-5">
          <div className="card">
            <div className="card-header text-center p-3">
              <h1 className='fs-4 mb-0'>Sign up to insta-delivery</h1>
            </div>
            <div className="card-body">
              <form>
                <div className="mb-3">
                  <label htmlFor="exampleInputEmail1" className="form-label">Username</label>
                  <input type="username" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
                </div>
                <div className="mb-3">
                  <label htmlFor="exampleInputEmail1" className="form-label">email address</label>
                  <input type="email" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" />
                </div>
                <div className="mb-3">
                  <label htmlFor="exampleInputPassword1" className="form-label">Password</label>
                  <input type="password" className="form-control" id="exampleInputPassword1" />
                </div>
                <div className="mb-3">
                  <label htmlFor="exampleInputPassword1" className="form-label">Cornfirm Password</label>
                  <input type="password" className="form-control" id="exampleInputPassword1" />
                </div>
                <Button variant='primary' type="submit" className="w-100">Create Account</Button>
              </form>
            </div>

            <div className="card-footer text-center p-3">
              <p className='mb-0'>Already have account to insta-delivery? <Link passHref shallow href="signin"><a className='text-decoration-none'>Sign In</a></Link> .</p>
            </div>
          </div>

        </div>
      </div>

    </div>
  )
}

export default SignUp
